language: ruby
env:
  global:
  - MAVEN_OPTS="-XX:MaxPermSize=512m"  
sudo: false
script:
- mkdir -p org.obeonetwork.aggregator/result/final/
- touch org.obeonetwork.aggregator/result/final/update-site.txt
#- mvn clean package -e -f org.obeonetwork.aggregator/pom.xml
- chmod a+x prepare-deploy-local-dir.sh
- "./prepare-deploy-local-dir.sh $TRAVIS_BUILD_DIR/nightly"
after_script:
- chmod a+x travis-promote.sh
- ./travis-promote.sh
deploy:
  matrix:
  - provider: s3
    access_key_id: AKIAI7GYGSUKTIBLAI6Q
    secret_access_key:
      secure: AkQHXay2Qful1BTGlS8EqR5uardszIoZVoxuYykNSQt34FtK43jL5nt/uaKckwDUjoHP4EhFpM/AW6bE6NSm0XVFSC3i3COsPxF4TjWj3cCcMZ8HwyIhm9gl6nb8mZnRWmhRbgoRxxpHkpBAk2bTIdBpKFPQxCNR0m8nrEGWD78=
    bucket: obeo-networkaggregation-releases
    local-dir: "${TRAVIS_BUILD_DIR}/nightly"
    acl: public_read
    skip_cleanup: true
    region: eu-west-1
    upload-dir: update/${TRAVIS_BRANCH}
    on:
      branch: sirius_3_0

